### ISSUE TITLE
ipopt options max_cpu_time and hessian_approximation cause a segmentation fault

### ISSUE THREAD

**Issue by ashutoshmahajan** [FOSSEE/FOSSEE-Optimization-toolbox#9]
Setting these two options causes the code to crash. Crashes all functions that use ipopt (version 3.12.4).
Possible workaround is to upgrade ipopt to the latest release version.

**Comment by JRGJON** [comment]
Updated Ipopt to latest version, but still crashed. The error was fixed by the following finding:

If the third party libraries are compiled in a particular linux OS(Example : Ubuntu 14.04), then the toolbox builder also has to be run in the same linux OS. The binaries that are created by running the builder files can be loaded on all Linux OS doesn't crash. If it is not builder is not run on the same version of OS, it crashes.
